### PR TITLE
Alias, getter and setter

### LINKED ISSUE #38: Set value programatically?
If I do this, I don't get "hola1"
only after the the second request I get proper value.

```
route::get('test',function(){
    Backpack\Settings\app\Models\Setting::where('key','MP_TOKEN')->update([
    'value'=>'hola1',
    ]);    
    echo Config::get('settings.MP_TOKEN');
});
```

wouldn't it be easier to have a 

`Config::set('key',value); `

to store value properly?

### LINKED ISSUE #57: Using config() inside Artisan
I read on here that it's not possible to use by default the `Config::get('setting here')` command with Artisan, so inside my Command Class, I've done the following:
```
use Backpack\Settings;
/**
* Create a new command instance.
*
* @return void
*/
public function __construct() {
    Settings::init();
    parent::__construct();
};
public function handle() {
    $this->info(Config::get('settings.program_status'));
}
```

But I'm getting this error thrown inside the console:

```
 [Symfony\Component\Debug\Exception\FatalThrowableError]  
  Class 'Backpack\Settings' not found     
```

How can I go about fixing this?

### PR DESCRIPTION
**Pull request by tabacitu**
This PR allows us to use these anywhere inside the app (including Console):
```php
Setting::get('key_name'); // will get the value from db
Setting::set('key_name', 'value'); // will update the value in db and config variable 
```

Fixes #38 
Fixes #57

### CODE REVIEW

File: src/app/Models/Setting.php [hunk 1]
```diff
@@ -11,4 +11,31 @@ class Setting extends Model
 
     protected $table = 'settings';
     protected $fillable = ['value'];
+
+    public static function get($key)
```
Comment (lloy0076) [inline src/app/Models/Setting.php]: The lack of PHP doc is disturbin.

File: src/app/Models/Setting.php [hunk 2]
```diff
@@ -11,4 +11,31 @@ class Setting extends Model
...
+        $entry = $setting->where('key', $key)->first();
+
+        if (!$entry) {
+            return;
+        }
+
+        return $entry->value;
+    }
+
+    public static function set($key, $value = null)
```
Comment (lloy0076) [inline src/app/Models/Setting.php]: PHP Doc.

File: src/app/Models/Setting.php [hunk 3]
```diff
@@ -11,4 +11,31 @@ class Setting extends Model
...
+    {
+        $setting = new self();
+        $entry = $setting->where('key', $key)->first();
+
+        if (!$entry) {
```
Comment (lloy0076) [inline src/app/Models/Setting.php]: I wonder if this should actually do a `firstOrFail` and just throw an exception.

Or `firstOrUpdate()`.

Or if this should make an entry if `$key` cannot be found.

File: src/app/Models/Setting.php [hunk 4]
```diff
@@ -11,4 +11,31 @@ class Setting extends Model
...
+            return false;
+        }
+
+        $entry->update(['value' => $value]);
```
Comment (lloy0076) [inline src/app/Models/Setting.php]: That can fail.

File: src/app/Models/Setting.php [hunk 5]
```diff
@@ -11,4 +11,31 @@ class Setting extends Model
...
+        \Config::set('settings.'.$key, $value);
```
Comment (lloy0076) [inline src/app/Models/Setting.php]: So can this.

File: src/app/Models/Setting.php [hunk 6]
```diff
@@ -11,4 +11,31 @@ class Setting extends Model
...
+
+        return true;
```
Comment (lloy0076) [inline src/app/Models/Setting.php]: But we return `true` still.

File: src/app/Models/Setting.php (hunk 1 above)
Comment (tabacitu) [reply src/app/Models/Setting.php]: Totally agree. At the time I thought "_heck, they're just getters and setters_". But now, let's do this right :-) Thank you for keeping me in check. Added in https://github.com/Laravel-Backpack/Settings/commit/3064341962c9018df725ac17fb2defee24f7eef7

File: src/app/Models/Setting.php (hunk 2 above)
Comment (tabacitu) [reply src/app/Models/Setting.php]: Done in https://github.com/Laravel-Backpack/Settings/commit/3064341962c9018df725ac17fb2defee24f7eef7

File: src/app/Models/Setting.php (hunk 3 above)
Comment (tabacitu) [reply src/app/Models/Setting.php]: True. ```firstOrFail()``` in https://github.com/Laravel-Backpack/Settings/commit/3064341962c9018df725ac17fb2defee24f7eef7

File: src/app/Models/Setting.php (hunk 4 above)
Comment (tabacitu) [reply src/app/Models/Setting.php]: True. ```saveOrFail()``` in https://github.com/Laravel-Backpack/Settings/commit/3064341962c9018df725ac17fb2defee24f7eef7

File: src/app/Models/Setting.php (hunk 5 above)
Comment (tabacitu) [reply src/app/Models/Setting.php]: True. Added check in https://github.com/Laravel-Backpack/Settings/commit/3064341962c9018df725ac17fb2defee24f7eef7

File: src/app/Models/Setting.php (hunk 6 above)
Comment (tabacitu) [reply src/app/Models/Setting.php]: Solved. Thank you!
